from __future__ import annotations
from typing import Any
ENDPOINTS={"health":"/health","diagnostics":"/diagnostics","discover":"/discover","entities":"/entities","state":"/state","config":"/config","config_sync":"/config/sync","deconfigure":"/deconfigure","ui_config":"/ui-config","events":"/events","command":"/command"}
REQUIRED_ENDPOINTS=["health","entities","command","config","ui_config"]
_UNITS={"connected":"bool","observed_at_ms":"ms","temperature_f":"F","humidity_percent":"%","pressure_relative_inhg":"inHg","pressure_absolute_inhg":"inHg","wind_speed_mph":"mph","wind_gust_mph":"mph","wind_gust_daily_max_mph":"mph","wind_direction_deg":"deg","rain_hourly_in":"in","rain_daily_in":"in","rain_weekly_in":"in","rain_monthly_in":"in","rain_yearly_in":"in","solar_radiation_wm2":"W/m2","uv_index":"index","feels_like_f":"F","dew_point_f":"F","indoor_temperature_f":"F","indoor_humidity_percent":"%","pm25_ugm3":"ug/m3","pm25_24h_ugm3":"ug/m3","pm25_aqi":"AQI","pm25_aqi_24h":"AQI","lightning_distance_mi":"mi","lightning_count":"count","soil_moisture_1_percent":"%","soil_moisture_2_percent":"%","soil_moisture_3_percent":"%","soil_moisture_4_percent":"%","outdoor_battery_ok":"bool","lightning_battery_ok":"bool"}
_UNITS.update({"temperature_c":"C","pressure_hpa":"hPa","wind_speed_mps":"m/s","wind_gust_mps":"m/s","rain_mm":"mm","lightning_distance_km":"km"})
for _index in range(1,11): _UNITS[f"sensor_{_index}_battery_ok"]="bool"
CAPABILITIES:dict[str,dict[str,Any]]={key:{"kind":"sensor","unit":unit} for key,unit in _UNITS.items()}
CAPABILITIES["refresh"]={"kind":"action"}
COMMANDS={"refresh":{"description":"Refresh Ambient Weather stations.","timeout_ms":15000}}
CONFIG_SCHEMA={"schema":{"title":"Ambient Weather Setup","type":"object","required":["application_key","api_key"],"properties":{"account_id":{"type":"string","title":"Account label","default":"ambient-weather"},"alias":{"type":"string","title":"Display name"},"application_key":{"type":"string","title":"Application key","writeOnly":True},"api_key":{"type":"string","title":"User API key","writeOnly":True},"poll_interval_seconds":{"type":"integer","minimum":60,"default":300}}},"uiSchema":{"application_key":{"ui:widget":"password"},"api_key":{"ui:widget":"password"}}}
FALLBACK_ENTITY={"id":"ambient-account","name":"Ambient Weather","device_id":"ambient-account","entity_type":"weather_station","capabilities":["connected","refresh"],"available_commands":[{"id":"refresh","label":"Refresh stations","kind":"action"}],"dashboard":{"allowed_widgets":["weather-station","tile","stat"],"default_widget":"weather-station"}}
